from _lib import Browser, BASE, check

with Browser() as b:
    p = b.page(375, 812)
    p.goto(BASE + "/")
    p.wait_for_load_state("networkidle")
    t = p.locator("button.nav-toggle")
    nav = p.locator("#site-nav")
    check(t.is_visible(), "toggle visible on phone")
    check(not nav.is_visible(), "nav hidden before toggle")
    t.click()
    check(t.get_attribute("aria-expanded") == "true" and nav.is_visible(), "opens")
    check(nav.locator("a").first.bounding_box()["height"] >= 44, "44px tap targets")
    p.keyboard.press("Escape")
    check(t.get_attribute("aria-expanded") == "false" and not nav.is_visible(), "Escape closes")
    check(p.evaluate("document.activeElement.classList.contains('nav-toggle')"), "focus returns to toggle")
    t.click()
    p.mouse.click(200, 700)
    check(t.get_attribute("aria-expanded") == "false", "outside click closes")
    t9 = b.page(900, 900)
    t9.goto(BASE + "/")
    check(t9.locator("button.nav-toggle").is_visible() and not t9.locator("#site-nav").is_visible(), "collapsed at 900px")
    d = b.page(1280, 900)
    d.goto(BASE + "/")
    check(not d.locator("button.nav-toggle").is_visible() and d.locator("#site-nav").is_visible(), "desktop nav inline")
    check(d.evaluate("getComputedStyle(document.querySelector('#site-nav a')).textTransform") == "uppercase", "nav uppercase")
    check(d.evaluate("Math.round(document.querySelector('.site-header .inner').getBoundingClientRect().height)") >= 124, "header 124px")
    check(b.errors == [], f"no console errors: {b.errors}")
