from _lib import Browser, BASE, check

with Browser() as b:
    p = b.page(1440, 900)
    p.goto(BASE + "/")
    p.wait_for_load_state("networkidle")
    check(p.title() == "Mohd Bilal — Korean Studies & Digital Humanities", "home title")
    check(p.locator("h1.page-title").inner_text().strip() == "Mohd Bilal", "page title is the name")
    check(p.locator("a.btn--primary[href='/about/']").inner_text().strip().startswith("More details"), "hero button to About")
    check(p.locator(".hero-fig img[alt*='長恨']").count() == 1 and p.locator(".hero-fig .caption").count() == 1, "hero image with caption")
    check(p.locator("section.band").count() >= 4, "at least four bands")
    check(p.locator(".pcard").count() == 3, "three project entries")
    check(p.locator(".pcard-counts > div").count() == 9, "every entry carries its counts")
    check(p.locator(".pcard-blurb").count() == 3, "every entry states its scope")
    check(p.locator("a.btn[href='/projects/']").inner_text().strip() == "View all projects »", "view all projects button")
    check(p.locator(".tile").count() >= 6, "news and talk tiles")
    check(p.locator("header nav a[aria-current='page']").text_content().strip() == "Home", "Home is current")
    check(p.evaluate("getComputedStyle(document.querySelector('h1.page-title')).fontFamily").startswith('"Playfair Display Variable"'), "Playfair title")
    check(p.evaluate("getComputedStyle(document.body).fontFamily").startswith('"Mulish Variable"'), "Mulish body")
    # hero stacks on tablet
    t = b.page(768, 1024)
    t.goto(BASE + "/")
    t.wait_for_load_state("networkidle")
    tx = t.evaluate("[document.querySelector('.hero-text').getBoundingClientRect().left, document.querySelector('.hero-fig').getBoundingClientRect().left]")
    check(round(tx[0]) == round(tx[1]), "hero stacks at 768px")
    check(b.errors == [], f"no console errors: {b.errors}")
