# The home page is a router: a thesis, one featured project, the index, and one committee path.
from _lib import Browser, BASE, check

with Browser() as b:
    p = b.page(1440, 900)
    p.goto(BASE + "/")
    p.wait_for_load_state("networkidle")
    check(p.title() == "Mohd Bilal — Korean Studies & Digital Humanities", "home title")
    h1 = p.locator("h1.page-title").inner_text().strip()
    check(len(h1) > 80 and h1.endswith("."), "the h1 is a thesis sentence, not a name")
    check("cannot support" in h1, "the thesis names the uncertainty commitment")
    check(p.locator(".whoami strong").inner_text().strip() == "Mohd Bilal", "name and affiliation below the thesis")
    check(p.locator(".feature-fig img[alt*='長恨']").count() == 1, "featured project carries a real image")
    check(p.locator(".feature-title a").count() == 1, "featured project links out")
    check(p.locator(".pindex .pitem").count() == 2, "the other two projects are listed")
    check(p.locator(".recent").count() == 1, "one recent line, not a news band")
    check(p.locator(".tile").count() == 0, "no tile bands")
    check(p.locator(".project-card").count() == 0, "no image cards")
    check(p.locator(".paths a[href='/files/mohd-bilal-cv.pdf']").count() == 1, "committee path offers the CV")
    check(len(p.locator("main").inner_text().split()) < 420, "home stays inside its word budget")
    check(p.evaluate("getComputedStyle(document.querySelector('h1.page-title')).fontFamily").startswith('"Playfair Display Variable"'), "Playfair title")
    check(p.evaluate("getComputedStyle(document.body).fontFamily").startswith('"Mulish Variable"'), "Mulish body")
    t = b.page(768, 1024)
    t.goto(BASE + "/")
    t.wait_for_load_state("networkidle")
    tx = t.evaluate("[document.querySelector('.feature-text').getBoundingClientRect().left, document.querySelector('.feature-fig').getBoundingClientRect().left]")
    check(round(tx[0]) == round(tx[1]), "feature stacks at 768px")
    check(b.errors == [], f"no console errors: {b.errors}")
