from _lib import Browser, BASE, check

with Browser() as b:
    p = b.page()
    p.goto(BASE + "/projects/buddhist-bridges/explore/")
    p.wait_for_load_state("networkidle")
    count = p.locator("#reg-count")
    inp = p.locator("#reg-search")
    check(count.inner_text().strip() == "43 of 43 mediators", "initial count")
    inp.fill("hye")
    check(count.inner_text().startswith("5 of 43"), "filtered count")
    inp.fill("zzzz")
    check(p.locator("#reg-empty").is_visible() and "zzzz" in p.locator("#reg-empty").inner_text(), "empty state names the query")
    p.locator("#reg-clear").click()
    check(count.inner_text().strip() == "43 of 43 mediators" and p.evaluate("document.activeElement.id") == "reg-search", "clear restores and refocuses")
    first = lambda: p.locator("#reg-table tbody tr[data-row]:not([hidden]) td.name").first.inner_text().strip()
    p.locator("#reg-table th button[data-sort='name']").click()
    asc = first()
    p.locator("#reg-table th button[data-sort='name']").click()
    desc = first()
    check(asc != desc and p.locator("#reg-table th[aria-sort='descending']").count() == 1, "name sort toggles with aria-sort")
    p.locator("#reg-table th button[data-sort='start']").click()
    check(p.locator("#reg-table th[aria-sort='ascending']").count() == 1, "date sort ascending")
    p.locator("#reg-table tbody tr[data-row]:not([hidden])").first.click()
    check(p.evaluate("document.getElementById('person-dialog').open"), "row opens record")
    p.keyboard.press("Escape")
    check(p.evaluate("document.activeElement.matches('tr[data-row]')"), "focus returns to the row")
    check(b.errors == [], f"no console errors: {b.errors}")
